name: WEA
dependencies:
  - pandas
  - jupyter
  - pip
  - python
  - matplotlib
  - openpyxl
  - pip:
    - windrose
    - reliability
    - DateTime
    - tk
    - scipy
    - tqdm
    - requests
    - bs4